### PR TITLE
Small adaptation to polymer 3

### LINKED ISSUE #10: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #10

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-lumo-styles/12)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[version.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12#-L827PxmeEueyVDOHkEI:-L827PxmeEueyVDOHkEJ:b-b39yna) ([raw file](https://github.com/vaadin/vaadin-lumo-styles/blob/1f1138d570607250b0b01343a381d35391b1b7a7/version.html#L6)):*
> ```HTML
>  */
> window.Vaadin = window.Vaadin || {};
> window.Vaadin.Lumo = {version: '1.0.0-beta2'};
> ```

Would it make sense to namespace this to `Vaadin.Lumo` so the module wouldn't export `Lumo.version` but just directly `version`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[version.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12#-L827PxmeEueyVDOHkEI:-L86iOAWOWaPNkALKpyD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-lumo-styles/blob/1f1138d570607250b0b01343a381d35391b1b7a7/version.html#L6)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Would it make sense to namespace this to `Vaadin.Lumo` so the module wouldn't export `Lumo.version` but just directly `version`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by tomivirkki** [comment]
*[version.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12#-L827PxmeEueyVDOHkEI:-L86ltafGIbMSltLxDqD:b-qsm3yf) ([raw file](https://github.com/vaadin/vaadin-lumo-styles/blob/1f1138d570607250b0b01343a381d35391b1b7a7/version.html#L6)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not a working fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[version.html, line 6 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12#-L827PxmeEueyVDOHkEI:-L8aFsx_6ExeXW-4JjgX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-lumo-styles/blob/1f1138d570607250b0b01343a381d35391b1b7a7/version.html#L6)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not a working fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12#-L8aILyQ3g_y_MMysNA7:-L8aILyQ3g_y_MMysNA8:b-j66q0j) (no related file):*
This PR is targeting master (should be p3-preview)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12#-:-L8aJKQtDPU8I-qIitU1:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12#-L8aILyQ3g_y_MMysNA7:-L8aNbZ3Eh9SvP4eGodd:b-a2ujfl) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This PR is targeting master (should be p3-preview)
</blockquote></details>

Changed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-lumo-styles/12)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-lumo-styles/12#-:-L8aOMW0PhVSn9wVBILT:bnfp4nl)*

**Pull request merged**
