### PR TITLE
Fix issue #83 required field: indicator jumps when setting required to false

### PR DESCRIPTION
**Pull request by AdrienC**

### CODE REVIEW

**Comment by jouni** [comment]
Another option would be to only add the indicator to the DOM when the field is actually required, but changing the selector from [`[part="label"]::after`](https://github.com/vaadin/vaadin-lumo-styles/pull/92/files#diff-9cc656237332d48ea28e16598c6a650dR35) to `:host([required]) [part="label"]::after, :host([invalid]) [part="label"]::after`.

That way, we wouldn’t be reserving space from the label on fields which never need to show the indicator.

**Comment by jouni** [comment]
Also, thank you for the PR 🤗 Always forget to start with that, before jumping straight to the topic 😊

**Comment by AdrienC** [comment]
Hi,
... but changing the selector like this would prevent the transition to happen : no more indicator fading to opacity 0 in 0.2s.
Which one is the prefered behaviour ?

**Comment by jouni** [comment]
The transition is desired when the user fills in a value to a required field. But not when the `required` attribute/property is toggled.

**Comment by web-padawan** [comment]
Sorry about leaving this PR open without any feedback. This fix will be included to https://github.com/vaadin/web-components/pull/2312

**Pull request closed without merging**
